areas:
  stubs:
    1.1.1.1: A B
    2.2.2.2: C D F
    3.3.3.3: L
  backbones:
    0.0.0.0: E G H

routers:
  - r12
  - r11
  - r21
  - r31
  - b012
  - b02
  - b03

costs:
  - b012 eth0 80
  - b02 eth3 80
  - b03 eth0 80